version: "3"

services:
  node-express-hello-world:
    container_name: node-express-hello-world
    image: odjhey/node-express-hello-world:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "node server.js"
    environment:
      PORT: "8080"
    labels:
      - traefik.http.routers.test3.rule=Host(`test.apps.domain.com`) && PathPrefix(`/bato`)
      - traefik.http.routers.test3.tls=true
      - traefik.http.routers.test3.tls.certresolver=lets-encrypt
      - traefik.port=8080
    networks:
      - web

networks:
  web:
    external: true
